/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SEATSYSTEM; 
import concert_ticketing_system.Viewmore1;
import java.util.HashMap;
/**
 *
 * @author Franzoli
 */
public class SEATSYSTEM1 extends javax.swing.JFrame {

    /**
     * Creates new form SEATSYSTEM1
     */
    public SEATSYSTEM1() {
        initComponents();
        
        
    }
    
    public String seatdata(){
        h
        return;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jButton73 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton73 = new javax.swing.JToggleButton();
        jToggleButton74 = new javax.swing.JToggleButton();
        jToggleButton75 = new javax.swing.JToggleButton();
        jToggleButton76 = new javax.swing.JToggleButton();
        jToggleButton77 = new javax.swing.JToggleButton();
        jToggleButton78 = new javax.swing.JToggleButton();
        jToggleButton79 = new javax.swing.JToggleButton();
        jToggleButton80 = new javax.swing.JToggleButton();
        jToggleButton81 = new javax.swing.JToggleButton();
        jToggleButton82 = new javax.swing.JToggleButton();
        jToggleButton83 = new javax.swing.JToggleButton();
        jToggleButton84 = new javax.swing.JToggleButton();
        jToggleButton85 = new javax.swing.JToggleButton();
        jToggleButton86 = new javax.swing.JToggleButton();
        jToggleButton87 = new javax.swing.JToggleButton();
        jToggleButton88 = new javax.swing.JToggleButton();
        jToggleButton89 = new javax.swing.JToggleButton();
        jToggleButton90 = new javax.swing.JToggleButton();
        jToggleButton91 = new javax.swing.JToggleButton();
        jToggleButton92 = new javax.swing.JToggleButton();
        jToggleButton93 = new javax.swing.JToggleButton();
        jToggleButton94 = new javax.swing.JToggleButton();
        jToggleButton95 = new javax.swing.JToggleButton();
        jToggleButton96 = new javax.swing.JToggleButton();
        jToggleButton97 = new javax.swing.JToggleButton();
        jToggleButton98 = new javax.swing.JToggleButton();
        jToggleButton99 = new javax.swing.JToggleButton();
        jToggleButton100 = new javax.swing.JToggleButton();
        jToggleButton101 = new javax.swing.JToggleButton();
        jToggleButton102 = new javax.swing.JToggleButton();
        jToggleButton103 = new javax.swing.JToggleButton();
        jToggleButton104 = new javax.swing.JToggleButton();
        jToggleButton105 = new javax.swing.JToggleButton();
        jToggleButton106 = new javax.swing.JToggleButton();
        jToggleButton107 = new javax.swing.JToggleButton();
        jToggleButton108 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton37 = new javax.swing.JToggleButton();
        jToggleButton38 = new javax.swing.JToggleButton();
        jToggleButton39 = new javax.swing.JToggleButton();
        jToggleButton40 = new javax.swing.JToggleButton();
        jToggleButton41 = new javax.swing.JToggleButton();
        jToggleButton42 = new javax.swing.JToggleButton();
        jToggleButton43 = new javax.swing.JToggleButton();
        jToggleButton44 = new javax.swing.JToggleButton();
        jToggleButton45 = new javax.swing.JToggleButton();
        jToggleButton46 = new javax.swing.JToggleButton();
        jToggleButton47 = new javax.swing.JToggleButton();
        jToggleButton48 = new javax.swing.JToggleButton();
        jToggleButton49 = new javax.swing.JToggleButton();
        jToggleButton50 = new javax.swing.JToggleButton();
        jToggleButton51 = new javax.swing.JToggleButton();
        jToggleButton52 = new javax.swing.JToggleButton();
        jToggleButton53 = new javax.swing.JToggleButton();
        jToggleButton54 = new javax.swing.JToggleButton();
        jToggleButton55 = new javax.swing.JToggleButton();
        jToggleButton56 = new javax.swing.JToggleButton();
        jToggleButton57 = new javax.swing.JToggleButton();
        jToggleButton58 = new javax.swing.JToggleButton();
        jToggleButton59 = new javax.swing.JToggleButton();
        jToggleButton60 = new javax.swing.JToggleButton();
        jToggleButton61 = new javax.swing.JToggleButton();
        jToggleButton62 = new javax.swing.JToggleButton();
        jToggleButton63 = new javax.swing.JToggleButton();
        jToggleButton64 = new javax.swing.JToggleButton();
        jToggleButton65 = new javax.swing.JToggleButton();
        jToggleButton66 = new javax.swing.JToggleButton();
        jToggleButton67 = new javax.swing.JToggleButton();
        jToggleButton68 = new javax.swing.JToggleButton();
        jToggleButton69 = new javax.swing.JToggleButton();
        jToggleButton70 = new javax.swing.JToggleButton();
        jToggleButton71 = new javax.swing.JToggleButton();
        jToggleButton72 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton35 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jToggleButton36 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(1200, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton73.setText("<-- Go back ");
        jButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton73ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stage");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 800, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Generic Admission");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jToggleButton73.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton73.setText("Seat 1");
        jToggleButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton73ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, 60));

        jToggleButton74.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton74.setText("Seat 2");
        jToggleButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton74ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, 60));

        jToggleButton75.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton75.setText("Seat 3");
        jToggleButton75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton75ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 60));

        jToggleButton76.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton76.setText("Seat 6");
        jToggleButton76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton76ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, 60));

        jToggleButton77.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton77.setText("Seat 5");
        jToggleButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton77ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, 60));

        jToggleButton78.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton78.setText("Seat 4");
        jToggleButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton78ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, 60));

        jToggleButton79.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton79.setText("Seat 7");
        jToggleButton79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton79ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, 60));

        jToggleButton80.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton80.setText("Seat 8");
        jToggleButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton80ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, 60));

        jToggleButton81.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton81.setText("Seat 9");
        jToggleButton81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton81ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, 60));

        jToggleButton82.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton82.setText("Seat 1");
        jToggleButton82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton82ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 60));

        jToggleButton83.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton83.setText("Seat 2");
        jToggleButton83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton83ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 60));

        jToggleButton84.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton84.setText("Seat 3");
        jToggleButton84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton84ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 60));

        jToggleButton85.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton85.setText("Seat 5");
        jToggleButton85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton85ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 60));

        jToggleButton86.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton86.setText("Seat 4");
        jToggleButton86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton86ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 60));

        jToggleButton87.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton87.setText("Seat 7");
        jToggleButton87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton87ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, 60));

        jToggleButton88.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton88.setText("Seat 8");
        jToggleButton88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton88ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, 60));

        jToggleButton89.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton89.setText("Seat 9");
        jToggleButton89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton89ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, 60));

        jToggleButton90.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton90.setText("Seat 6");
        jToggleButton90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton90ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, 60));

        jToggleButton91.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton91.setText("Seat 1");
        jToggleButton91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton91ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton91, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, 60));

        jToggleButton92.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton92.setText("Seat 4");
        jToggleButton92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton92ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton92, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, 60));

        jToggleButton93.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton93.setText("Seat 7");
        jToggleButton93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton93ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton93, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, -1, 60));

        jToggleButton94.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton94.setText("Seat 8");
        jToggleButton94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton94ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton94, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, -1, 60));

        jToggleButton95.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton95.setText("Seat 5");
        jToggleButton95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton95ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, -1, 60));

        jToggleButton96.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton96.setText("Seat 2");
        jToggleButton96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton96ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, 60));

        jToggleButton97.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton97.setText("Seat 3");
        jToggleButton97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton97ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, 60));

        jToggleButton98.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton98.setText("Seat 6");
        jToggleButton98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton98ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, -1, 60));

        jToggleButton99.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton99.setText("Seat 9");
        jToggleButton99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton99ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, -1, 60));

        jToggleButton100.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton100.setText("Seat 7");
        jToggleButton100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton100ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, -1, 60));

        jToggleButton101.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton101.setText("Seat 8");
        jToggleButton101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton101ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton101, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 160, -1, 60));

        jToggleButton102.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton102.setText("Seat 9");
        jToggleButton102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton102ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton102, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 160, -1, 60));

        jToggleButton103.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton103.setText("Seat 6");
        jToggleButton103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton103ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton103, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 90, -1, 60));

        jToggleButton104.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton104.setText("Seat 5");
        jToggleButton104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton104ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton104, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 90, -1, 60));

        jToggleButton105.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton105.setText("Seat 4");
        jToggleButton105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton105ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton105, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 90, -1, 60));

        jToggleButton106.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton106.setText("Seat 1");
        jToggleButton106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton106ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton106, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, -1, 60));

        jToggleButton107.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton107.setText("Seat 2");
        jToggleButton107.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton107ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton107, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, -1, 60));

        jToggleButton108.setBackground(new java.awt.Color(255, 153, 51));
        jToggleButton108.setText("Seat 3");
        jToggleButton108.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton108ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton108, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, -1, 60));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 1290, 250));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("General Admission");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jToggleButton37.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton37.setText("Seat 1");
        jToggleButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton37ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 60));

        jToggleButton38.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton38.setText("Seat 2");
        jToggleButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton38ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 60));

        jToggleButton39.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton39.setText("Seat 3");
        jToggleButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton39ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 60));

        jToggleButton40.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton40.setText("Seat 4");
        jToggleButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton40ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, 60));

        jToggleButton41.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton41.setText("Seat 5");
        jToggleButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton41ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 60));

        jToggleButton42.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton42.setText("Seat 6");
        jToggleButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton42ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, 60));

        jToggleButton43.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton43.setText("Seat 7");
        jToggleButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton43ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, 60));

        jToggleButton44.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton44.setText("Seat 8");
        jToggleButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton44ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 60));

        jToggleButton45.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton45.setText("Seat 9");
        jToggleButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton45ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, 60));

        jToggleButton46.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton46.setText("Seat 1");
        jToggleButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton46ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, 60));

        jToggleButton47.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton47.setText("Seat 2");
        jToggleButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton47ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, 60));

        jToggleButton48.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton48.setText("Seat 3");
        jToggleButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton48ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, 60));

        jToggleButton49.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton49.setText("Seat 4");
        jToggleButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton49ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 60));

        jToggleButton50.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton50.setText("Seat 5");
        jToggleButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton50ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 60));

        jToggleButton51.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton51.setText("Seat 6");
        jToggleButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton51ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, 60));

        jToggleButton52.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton52.setText("Seat 7");
        jToggleButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton52ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, 60));

        jToggleButton53.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton53.setText("Seat 8");
        jToggleButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton53ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, 60));

        jToggleButton54.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton54.setText("Seat 9");
        jToggleButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton54ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, 60));

        jToggleButton55.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton55.setText("Seat 1");
        jToggleButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton55ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, 60));

        jToggleButton56.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton56.setText("Seat 2");
        jToggleButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton56ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, -1, 60));

        jToggleButton57.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton57.setText("Seat 3");
        jToggleButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton57ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, 60));

        jToggleButton58.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton58.setText("Seat 4");
        jToggleButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton58ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, 60));

        jToggleButton59.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton59.setText("Seat 5");
        jToggleButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton59ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, -1, 60));

        jToggleButton60.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton60.setText("Seat 6");
        jToggleButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton60ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, -1, 60));

        jToggleButton61.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton61.setText("Seat 7");
        jToggleButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton61ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, -1, 60));

        jToggleButton62.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton62.setText("Seat 8");
        jToggleButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton62ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, -1, 60));

        jToggleButton63.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton63.setText("Seat 9");
        jToggleButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton63ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, -1, 60));

        jToggleButton64.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton64.setText("Seat 1");
        jToggleButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton64ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, -1, 60));

        jToggleButton65.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton65.setText("Seat 2");
        jToggleButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton65ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, -1, 60));

        jToggleButton66.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton66.setText("Seat 3");
        jToggleButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton66ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, -1, 60));

        jToggleButton67.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton67.setText("Seat 4");
        jToggleButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton67ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, -1, 60));

        jToggleButton68.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton68.setText("Seat 5");
        jToggleButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton68ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 100, -1, 60));

        jToggleButton69.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton69.setText("Seat 6");
        jToggleButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton69ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 100, -1, 60));

        jToggleButton70.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton70.setText("Seat 7");
        jToggleButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton70ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, -1, 60));

        jToggleButton71.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton71.setText("Seat 8");
        jToggleButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton71ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, -1, 60));

        jToggleButton72.setBackground(new java.awt.Color(255, 51, 255));
        jToggleButton72.setText("Seat 9");
        jToggleButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton72ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 170, -1, 60));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 1290, 240));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Vip");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Standing ");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jToggleButton10.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton10.setText("Seat 1");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 60));

        jToggleButton11.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton11.setText("Seat 4");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 60));

        jToggleButton12.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton12.setText("Seat 7");
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 60));

        jToggleButton13.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton13.setText("Seat 8");
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 60));

        jToggleButton14.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton14.setText("Seat 5");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, 60));

        jToggleButton15.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton15.setText("Seat 2");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 60));

        jToggleButton16.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton16.setText("Seat 3");
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 60));

        jToggleButton17.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton17.setText("Seat 6");
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, 60));

        jToggleButton18.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton18.setText("Seat 9");
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, 60));

        jToggleButton19.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton19.setText("Seat 1");
        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton19ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 60));

        jToggleButton20.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton20.setText("Seat 4");
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, 60));

        jToggleButton21.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton21.setText("Seat 7");
        jToggleButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton21ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, 60));

        jToggleButton22.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton22.setText("Seat 8");
        jToggleButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton22ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, 60));

        jToggleButton23.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton23.setText("Seat 5");
        jToggleButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton23ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, 60));

        jToggleButton24.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton24.setText("Seat 2");
        jToggleButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton24ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, 60));

        jToggleButton25.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton25.setText("Seat 3");
        jToggleButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton25ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, 60));

        jToggleButton26.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton26.setText("Seat 6");
        jToggleButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton26ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, 60));

        jToggleButton27.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton27.setText("Seat 9");
        jToggleButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton27ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 60));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 650, 220));

        jToggleButton1.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton1.setText("Seat 3");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 60));

        jToggleButton2.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton2.setText("Seat 1");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 60));

        jToggleButton3.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton3.setText("Seat 2");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 60));

        jToggleButton4.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton4.setText("Seat 4");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 60));

        jToggleButton5.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton5.setText("Seat 5");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 60));

        jToggleButton6.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton6.setText("Seat 6");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 60));

        jToggleButton7.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton7.setText("Seat 7");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 60));

        jToggleButton8.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton8.setText("Seat 8");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, 60));

        jToggleButton9.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton9.setText("Seat 9");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, 60));

        jToggleButton30.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton30.setText("Seat 7");
        jToggleButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton30ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, -1, 60));

        jToggleButton29.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton29.setText("Seat 4");
        jToggleButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, -1, 60));

        jToggleButton31.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton31.setText("Seat 8");
        jToggleButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 160, -1, 60));

        jToggleButton28.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton28.setText("Seat 1");
        jToggleButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, 60));

        jToggleButton33.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton33.setText("Seat 2");
        jToggleButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, 60));

        jToggleButton34.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton34.setText("Seat 3");
        jToggleButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton34ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, -1, 60));

        jToggleButton35.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton35.setText("Seat 6");
        jToggleButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton35ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 90, -1, 60));

        jToggleButton32.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton32.setText("Seat 5");
        jToggleButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, -1, 60));

        jToggleButton36.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton36.setText("Seat 9");
        jToggleButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton36ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 160, -1, 60));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1290, 240));

        jScrollPane1.setViewportView(jPanel6);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1320, 740));

        setBounds(0, 0, 1345, 763);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
        // TODO add your handling code here:
        // back button
        this.dispose();
        this.setVisible(false);
       Viewmore1 VW1 = new Viewmore1();
       VW1.setVisible(true);
      
        
    }//GEN-LAST:event_jButton73ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        boolean seat1sel = true;
        if(jToggleButton2.isSelected()){
            System.out.println("button seat1 selected");
        }else{
            System.out.println("button seat1 deselected");
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton19ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton21ActionPerformed

    private void jToggleButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton22ActionPerformed

    private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton23ActionPerformed

    private void jToggleButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton24ActionPerformed

    private void jToggleButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton25ActionPerformed

    private void jToggleButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton26ActionPerformed

    private void jToggleButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton27ActionPerformed

    private void jToggleButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton28ActionPerformed

    private void jToggleButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton29ActionPerformed

    private void jToggleButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton30ActionPerformed

    private void jToggleButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton31ActionPerformed

    private void jToggleButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton32ActionPerformed

    private void jToggleButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton33ActionPerformed

    private void jToggleButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton34ActionPerformed

    private void jToggleButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton35ActionPerformed

    private void jToggleButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton36ActionPerformed

    private void jToggleButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton37ActionPerformed

    private void jToggleButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton38ActionPerformed

    private void jToggleButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton39ActionPerformed

    private void jToggleButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton40ActionPerformed

    private void jToggleButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton41ActionPerformed

    private void jToggleButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton42ActionPerformed

    private void jToggleButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton43ActionPerformed

    private void jToggleButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton44ActionPerformed

    private void jToggleButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton45ActionPerformed

    private void jToggleButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton46ActionPerformed

    private void jToggleButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton47ActionPerformed

    private void jToggleButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton48ActionPerformed

    private void jToggleButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton49ActionPerformed

    private void jToggleButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton50ActionPerformed

    private void jToggleButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton51ActionPerformed

    private void jToggleButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton52ActionPerformed

    private void jToggleButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton53ActionPerformed

    private void jToggleButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton54ActionPerformed

    private void jToggleButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton55ActionPerformed

    private void jToggleButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton56ActionPerformed

    private void jToggleButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton57ActionPerformed

    private void jToggleButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton58ActionPerformed

    private void jToggleButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton59ActionPerformed

    private void jToggleButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton60ActionPerformed

    private void jToggleButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton61ActionPerformed

    private void jToggleButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton62ActionPerformed

    private void jToggleButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton63ActionPerformed

    private void jToggleButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton64ActionPerformed

    private void jToggleButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton65ActionPerformed

    private void jToggleButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton66ActionPerformed

    private void jToggleButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton67ActionPerformed

    private void jToggleButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton68ActionPerformed

    private void jToggleButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton69ActionPerformed

    private void jToggleButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton70ActionPerformed

    private void jToggleButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton71ActionPerformed

    private void jToggleButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton72ActionPerformed

    private void jToggleButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton73ActionPerformed

    private void jToggleButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton74ActionPerformed

    private void jToggleButton75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton75ActionPerformed

    private void jToggleButton76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton76ActionPerformed

    private void jToggleButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton77ActionPerformed

    private void jToggleButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton78ActionPerformed

    private void jToggleButton79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton79ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton79ActionPerformed

    private void jToggleButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton80ActionPerformed

    private void jToggleButton81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton81ActionPerformed

    private void jToggleButton82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton82ActionPerformed

    private void jToggleButton83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton83ActionPerformed

    private void jToggleButton84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton84ActionPerformed

    private void jToggleButton85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton85ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton85ActionPerformed

    private void jToggleButton86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton86ActionPerformed

    private void jToggleButton87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton87ActionPerformed

    private void jToggleButton88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton88ActionPerformed

    private void jToggleButton89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton89ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton89ActionPerformed

    private void jToggleButton90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton90ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton90ActionPerformed

    private void jToggleButton91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton91ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton91ActionPerformed

    private void jToggleButton92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton92ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton92ActionPerformed

    private void jToggleButton93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton93ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton93ActionPerformed

    private void jToggleButton94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton94ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton94ActionPerformed

    private void jToggleButton95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton95ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton95ActionPerformed

    private void jToggleButton96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton96ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton96ActionPerformed

    private void jToggleButton97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton97ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton97ActionPerformed

    private void jToggleButton98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton98ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton98ActionPerformed

    private void jToggleButton99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton99ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton99ActionPerformed

    private void jToggleButton100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton100ActionPerformed

    private void jToggleButton101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton101ActionPerformed

    private void jToggleButton102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton102ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton102ActionPerformed

    private void jToggleButton103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton103ActionPerformed

    private void jToggleButton104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton104ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton104ActionPerformed

    private void jToggleButton105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton105ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton105ActionPerformed

    private void jToggleButton106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton106ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton106ActionPerformed

    private void jToggleButton107ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton107ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton107ActionPerformed

    private void jToggleButton108ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton108ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton108ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEATSYSTEM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEATSYSTEM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEATSYSTEM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEATSYSTEM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEATSYSTEM1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton73;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton100;
    private javax.swing.JToggleButton jToggleButton101;
    private javax.swing.JToggleButton jToggleButton102;
    private javax.swing.JToggleButton jToggleButton103;
    private javax.swing.JToggleButton jToggleButton104;
    private javax.swing.JToggleButton jToggleButton105;
    private javax.swing.JToggleButton jToggleButton106;
    private javax.swing.JToggleButton jToggleButton107;
    private javax.swing.JToggleButton jToggleButton108;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton37;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton39;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton40;
    private javax.swing.JToggleButton jToggleButton41;
    private javax.swing.JToggleButton jToggleButton42;
    private javax.swing.JToggleButton jToggleButton43;
    private javax.swing.JToggleButton jToggleButton44;
    private javax.swing.JToggleButton jToggleButton45;
    private javax.swing.JToggleButton jToggleButton46;
    private javax.swing.JToggleButton jToggleButton47;
    private javax.swing.JToggleButton jToggleButton48;
    private javax.swing.JToggleButton jToggleButton49;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton50;
    private javax.swing.JToggleButton jToggleButton51;
    private javax.swing.JToggleButton jToggleButton52;
    private javax.swing.JToggleButton jToggleButton53;
    private javax.swing.JToggleButton jToggleButton54;
    private javax.swing.JToggleButton jToggleButton55;
    private javax.swing.JToggleButton jToggleButton56;
    private javax.swing.JToggleButton jToggleButton57;
    private javax.swing.JToggleButton jToggleButton58;
    private javax.swing.JToggleButton jToggleButton59;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton60;
    private javax.swing.JToggleButton jToggleButton61;
    private javax.swing.JToggleButton jToggleButton62;
    private javax.swing.JToggleButton jToggleButton63;
    private javax.swing.JToggleButton jToggleButton64;
    private javax.swing.JToggleButton jToggleButton65;
    private javax.swing.JToggleButton jToggleButton66;
    private javax.swing.JToggleButton jToggleButton67;
    private javax.swing.JToggleButton jToggleButton68;
    private javax.swing.JToggleButton jToggleButton69;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton70;
    private javax.swing.JToggleButton jToggleButton71;
    private javax.swing.JToggleButton jToggleButton72;
    private javax.swing.JToggleButton jToggleButton73;
    private javax.swing.JToggleButton jToggleButton74;
    private javax.swing.JToggleButton jToggleButton75;
    private javax.swing.JToggleButton jToggleButton76;
    private javax.swing.JToggleButton jToggleButton77;
    private javax.swing.JToggleButton jToggleButton78;
    private javax.swing.JToggleButton jToggleButton79;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton80;
    private javax.swing.JToggleButton jToggleButton81;
    private javax.swing.JToggleButton jToggleButton82;
    private javax.swing.JToggleButton jToggleButton83;
    private javax.swing.JToggleButton jToggleButton84;
    private javax.swing.JToggleButton jToggleButton85;
    private javax.swing.JToggleButton jToggleButton86;
    private javax.swing.JToggleButton jToggleButton87;
    private javax.swing.JToggleButton jToggleButton88;
    private javax.swing.JToggleButton jToggleButton89;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JToggleButton jToggleButton90;
    private javax.swing.JToggleButton jToggleButton91;
    private javax.swing.JToggleButton jToggleButton92;
    private javax.swing.JToggleButton jToggleButton93;
    private javax.swing.JToggleButton jToggleButton94;
    private javax.swing.JToggleButton jToggleButton95;
    private javax.swing.JToggleButton jToggleButton96;
    private javax.swing.JToggleButton jToggleButton97;
    private javax.swing.JToggleButton jToggleButton98;
    private javax.swing.JToggleButton jToggleButton99;
    // End of variables declaration//GEN-END:variables
}
